#!/usr/bin/env bash        
# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 

imagefile=/afs/ihep.ac.cn/users/s/shixin/raser/raser-4.0.sif
export PATH=/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:$PATH

raser(){
    apptainer exec --env-file cfg/env -B /cefs,/afs,/besfs5,/cvmfs,/scratchfs,/workfs2 $imagefile $1 
}

usage() { 
    printf "NAME\n"
    printf "\t%s\n" "run - Main driver to run RASER"
    printf "\n"

    printf "SYNOPSIS\n"
    printf "\t%s\n" "./run [OPTION]"
    printf "\n"

    printf "OPTIONS\n"    
    printf "\t%-8s %-40s\n"    "1"       "Electric Profile"
    printf "\t%-8s %-40s\n"    "2"       "Particle Injection"
    printf "\t%-8s %-40s\n"    "3"       "Current Induction"
    printf "\t%-8s %-40s\n"    "4"       "Electronics"
    printf "\t%-8s %-40s\n"    "5"       "Time Resolution"
    printf "\t%-8s %-40s\n"    "6"       "Space Resolution"
    printf "\t%-8s %-40s\n"    "7"       "Transient Current Technique"
    printf "\n"
}

if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
    option=$1 
	input_para=$* 
fi

case $option in 
    1.1) echo "RASER simulate NJU-PIN"
        usage_1_1
        echo "Please enter your option: " 
        read option 
        sub_1_1 option 
        ;;
    1.1.*) echo "RASER simulate NJU-PIN"
        sub_1_1 option
        ;;
esac
