#!/usr/bin/env bash        

# Main driver to run RASER    
# Author SHI Xin <shixin@ihep.ac.cn>  
# Created [2021-03-21 Sun 10:04] 


usage() { 
    printf "NAME\n\trun - Main driver to run RASER\n"
    printf "\nSYNOPSIS\n"
    printf "\n\t%-5s\n" "./run [OPTION]" 
    printf "\nOPTIONS\n"    
    printf "\n\t%-9s  %-40s"  "0.1"       "RASER 3D Angle"
    printf "\n\n" 
}

usage_0_1() { 
    printf "\n\t%-5s  %-40s\n"  "0.1.1"    " Angle research " 
}

if [[ $# -eq 0 ]]; then
    usage
    echo "Please enter your option: "
    read option
else
	source singularity/singularity_bashrc.sh	
    option=$1 
	input_para=$* 
fi

sub_0_1(){
case $option in 

    0.1.1) echo " Source angle research for planar detector"
        ./python/sangle.py det_model=planar3D parfile=setting.json angle=0
        ;;

    0.1.2) echo " Source angle research for plugin3D detector"
        ./python/sangle.py det_model=plugin3D parfile=setting.json angle=0
        ;;
		esac
}
 

case $option in 
   0.1) echo "RASER planar3D"
        usage_0_1
        echo "Please enter your option: " 
        read option 
        sub_0_1 option 
        ;;
    0.1.*) echo "RASER planar3D"
        sub_0_1 option
        ;;
		esac
